version: '3.4'

networks:
    myAppNetwork:   

services:
  
  sqldata:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest   
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=Password1#
    networks:
      - myAppNetwork

  webapibankingsystem:
    container_name: webApiBankignSystemContainer
    image: ${DOCKER_REGISTRY-}webapibankingsystem
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: WebApiBankingSystem/Dockerfile
    depends_on:
      - sqldata
    networks:
      - myAppNetwork